- id: '1572916920034'
  alias: 'Sensor: Notify Kais if motion is detected when not home'
  description: ''
  trigger:
  - device_id: 65529a4b828041108316728880340a6c
    domain: binary_sensor
    entity_id: binary_sensor.motion_1_occupancy
    platform: device
    type: motion
  - device_id: b87abad6254647268b2f333db3b2a5e5
    domain: binary_sensor
    entity_id: binary_sensor.motion_2_occupancy
    platform: device
    type: motion
  - device_id: 2cd27ab0affa43c7bc7265cc4ed90c04
    domain: binary_sensor
    entity_id: binary_sensor.front_door_contact
    platform: device
    type: opened
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
  action:
  - data:
      message: Sensors triggered at home! 🕵🏻‍♂️
    service: notify.ios_iphone_11_pro
- id: '1575004627821'
  alias: 'Lights: Turn on the living room lights using switch'
  description: ''
  trigger:
  - entity_id: sensor.light_switch_click
    platform: state
    to: 'on'
  condition:
  - condition: device
    device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: is_on
  action:
  - scene: scene.living_room_normal
- id: '1575004958830'
  alias: 'Lights: Turn off the living room lights using switch'
  description: ''
  trigger:
  - entity_id: sensor.light_switch_click
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: turn_off
  - device_id: 696174e7edb34ab7961d233900e11e28
    domain: switch
    entity_id: switch.led_lights_switch
    type: turn_off
- id: '1575163193342'
  alias: 'Lights: Turn on the living room lights when Hall motion is detected'
  description: ''
  trigger:
  - device_id: b87abad6254647268b2f333db3b2a5e5
    domain: binary_sensor
    entity_id: binary_sensor.motion_2_occupancy
    platform: device
    type: motion
  condition:
  - condition: and
    conditions:
    - after: sunset
      after_offset: -01:00:00
      condition: sun
    - before: '23:59:59'
      condition: time
  - below: 5
    condition: device
    device_id: 34079b50d2bd46a781e9813584b42f90
    domain: sensor
    entity_id: sensor.livingroom_light
    type: is_illuminance
  action:
  - device_id: 696174e7edb34ab7961d233900e11e28
    domain: switch
    entity_id: switch.led_lights_switch
    type: turn_on
  - device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: turn_on
- id: '1575163662407'
  alias: 'Lights: Turn off the lights when everyone leaves home'
  description: ''
  trigger:
  - entity_id: group.family
    from: home
    platform: state
  condition: []
  action:
  - device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: turn_off
  - device_id: 696174e7edb34ab7961d233900e11e28
    domain: switch
    entity_id: switch.led_lights_switch
    type: turn_off
  - device_id: 5415x25052r7icro30839514h8lb07iz
    domain: light
    entity_id: light.bedroom
    type: turn_off
  - device_id: 9da02b33e97444d8a768935b358cd4b9
    domain: light
    entity_id: light.kitchen
    type: turn_off
- id: '1575259801458'
  alias: 'Lights: Turn on the bedroom light when motion is detected'
  description: ''
  trigger:
  - device_id: 65529a4b828041108316728880340a6c
    domain: binary_sensor
    entity_id: binary_sensor.motion_1_occupancy
    platform: device
    type: motion
  condition:
  - condition: and
    conditions:
    - after: sunset
      after_offset: -00:30:00
      condition: sun
    - before: '23:59:59'
      condition: time
    - below: 5
      condition: device
      device_id: f8704551f8ad4e73b9986af69f2c776a
      domain: sensor
      entity_id: sensor.bedroom_light
      type: is_illuminance
  action:
  - scene: scene.bedroom_normal
- id: '1575261065811'
  alias: 'Lights: Turn off the bedroom light when no motion is detected'
  description: ''
  trigger:
  - device_id: 65529a4b828041108316728880340a6c
    domain: binary_sensor
    entity_id: binary_sensor.motion_1_occupancy
    for:
      hours: 0
      minutes: 3
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: 5415x25052r7icro30839514h8lb07iz
    domain: light
    entity_id: light.bedroom
    type: turn_off
- id: '1575261423692'
  alias: 'Lights: Dim living room when media is playing'
  description: ''
  trigger:
  - entity_id: media_player.plex_fire_tv
    from: paused
    platform: state
    to: playing
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - scene: scene.living_room_dimmed
- id: '1575261572979'
  alias: 'Lights: Undim living room lights when media is paused'
  description: ''
  trigger:
  - entity_id: media_player.plex_fire_tv
    from: playing
    platform: state
  condition:
  - after: sunset
    before: sunrise
    condition: sun
  action:
  - scene: scene.living_room_normal
- id: '1575266815789'
  alias: 'Lights: Turn on the living room lights (dimmed) using switch'
  description: ''
  trigger:
  - entity_id: sensor.light_switch_click
    platform: state
    to: 'on'
  condition:
  - condition: device
    device_id: 696174e7edb34ab7961d233900e11e28
    domain: switch
    entity_id: switch.led_lights_switch
    type: is_off
  - condition: device
    device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: is_off
  action:
  - scene: scene.living_room_dimmed
- id: '1575882844623'
  alias: 'Lights: Turn off the lights when in bed'
  description: ''
  trigger:
  - entity_id: binary_sensor.kais_in_bed
    platform: state
    to: 'on'
  - entity_id: binary_sensor.karine_in_bed
    platform: state
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.karine_in_bed
      state: 'on'
    - condition: state
      entity_id: binary_sensor.kais_in_bed
      state: 'on'
  action:
  - device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: turn_off
  - device_id: 696174e7edb34ab7961d233900e11e28
    domain: switch
    entity_id: switch.led_lights_switch
    type: turn_off
- id: '1576050278007'
  alias: 'Sensor: Send a notification when Kais in bed'
  description: ''
  trigger:
  - entity_id: binary_sensor.kais_in_bed
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Good night 🛌😴
    service: notify.ios_iphone_11_pro
- id: '1576050676881'
  alias: 'Sensor: Send a notification when Karine in bed'
  description: ''
  trigger:
  - entity_id: binary_sensor.karine_in_bed
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Good night 🛌😴
    service: notify.mobile_app_karines_iphone
- id: '1576831285153'
  alias: 'Vacuum: Cleanup entrance when someone gets home'
  description: ''
  trigger:
  - entity_id: group.family
    platform: state
    to: home
  condition:
  - after: '10:00'
    before: '21:00'
    condition: time
  action:
  - delay: 00:15:00
  - data:
      command: zoned_cleanup
      entity_id: vacuum.rockrobo
      params:
        zone_ids:
        - Hall
    entity_id: vacuum.rockrobo
    service: vacuum.send_command
- id: '1576872918301'
  alias: 'Vacuum: Cleaning started'
  description: ''
  trigger:
  - entity_id: vacuum.rockrobo
    from: docked
    platform: state
    to: cleaning
  condition: []
  action:
  - data:
      message: '🤖🧹: I''ve started cleaning!'
      title: Robot
    service: notify.mobile_app_iphone_11_pro
- id: '1576872978100'
  alias: 'Vacuum: Cleaning stopped'
  description: ''
  trigger:
  - entity_id: vacuum.rockrobo
    from: returning
    platform: state
    to: docked
  condition: []
  action:
  - data:
      message: '🤖🧹: I''ve finished cleaning after {{ (state_attr(''vacuum.rockrobo'',
        ''last_run_stats'').duration/60) | round(0) }} minutes!'
      title: Robot
    service: notify.mobile_app_iphone_11_pro
  - entity_id: input_boolean.cleaned_today
    service: input_boolean.turn_on
- id: '1576873721439'
  alias: 'Vacuum: Cleanup when nobody is home'
  description: ''
  trigger:
  - entity_id: group.family
    from: home
    platform: state
  condition:
  - condition: and
    conditions:
    - after: '11:00'
      before: '22:00'
      condition: time
    - condition: state
      entity_id: input_boolean.cleaned_today
      state: 'off'
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'
  action:
  - alias: ''
    data:
      command: zoned_cleanup
      entity_id: vacuum.rockrobo
      params:
        zone_ids:
        - Hall
        - Kitchen
        - Living Room
        - Bedroom
        - Bathroom
        - Den
    entity_id: vacuum.rockrobo
    service: vacuum.send_command
- id: '1576874192711'
  alias: 'Vacuum: Reset cleaning counter'
  description: ''
  trigger:
  - at: 00:00:01
    platform: time
  condition: []
  action:
  - entity_id: input_boolean.cleaned_today
    service: input_boolean.turn_off
- id: '1584158523689'
  alias: 'Sensor: Notify Kais when the bedroom temperature is low in the evening'
  description: ''
  trigger:
  - at: '21:30:00'
    platform: time
  condition:
  - below: '19'
    condition: numeric_state
    entity_id: sensor.bedroom_temperature
  action:
  - data:
      message: Don't forget to turn on the bedroom heater 🛌🥶
    service: notify.ios_iphone_11_pro
- id: '1584438260170'
  alias: 'Sensor: Notify Kais when the living room temperature is high during the
    day'
  description: ''
  trigger:
  - at: '12:00:00'
    platform: time
  - at: '16:00:00'
    platform: time
  condition:
  - above: '20'
    condition: numeric_state
    entity_id: sensor.livingroom_temperature
  - above: '20'
    condition: numeric_state
    entity_id: sensor.bedroom_temperature
  action:
  - data:
      message: Don't forget to turn off the heaters 🏠🔥🥵
    service: notify.ios_iphone_11_pro
- id: '1591907544710'
  alias: 'Lights: Turn on the living room when light level is low'
  description: ''
  trigger:
  - below: 10
    device_id: 34079b50d2bd46a781e9813584b42f90
    domain: sensor
    entity_id: sensor.livingroom_light
    for:
      hours: 0
      minutes: 0
      seconds: 15
    platform: device
    type: illuminance
  condition: []
  action:
  - scene: scene.living_room_normal
- id: '1591988789043'
  alias: 'Lights: Turn off living room lights when intensity is high'
  description: ''
  trigger:
  - above: 15
    device_id: 34079b50d2bd46a781e9813584b42f90
    domain: sensor
    entity_id: sensor.livingroom_light
    for:
      hours: 0
      minutes: 0
      seconds: 15
    platform: device
    type: illuminance
  condition: []
  action:
  - device_id: 3c7b03507e4340f699ab93684c061d53
    domain: light
    entity_id: light.bulb_light
    type: turn_off
  - device_id: 696174e7edb34ab7961d233900e11e28
    domain: switch
    entity_id: switch.led_lights_switch
    type: turn_off
