- platform: generic
  still_image_url: !secret vacuum_map_url
  name: Vacuum map
  framerate: 1
- platform: local_file
  file_path: www/radar/snow_radar.gif
  name: Snow Radar
- platform: generic
  still_image_url: https://mtseymour.ca/webcam_image.php?cam=1
  name: Mt Seymour Main
- platform: generic
  still_image_url: https://mtseymour.ca/webcam_image.php?cam=2
  name: Mt Seymour Weather
- platform: generic
  still_image_url: https://mtseymour.ca/webcam_image.php?cam=3
  name: Mt Seymour Snowruler
- platform: combined
  name: Mt Seymour
  base_address: https://home.kaisbn.fr
  entities:
    - camera.mt_seymour_main
    - camera.mt_seymour_weather
- platform: combined
  name: Snow Report
  base_address: https://home.kaisbn.fr
  entities:
    - camera.snow_radar
    - camera.mt_seymour_snowruler
