alexa:
  smart_home:
    filter: !include filter.yaml

api:

automation: !include automations.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include cameras.yaml

config:

device_tracker: !include device_trackers.yaml

discovery:
  ignore:
    - google_cast

emulated_hue:
  listen_port: 80

fontawesome:
  regular:
  solid:
  brands:

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml

history:
  include:
    domains:
      - binary_sensor
      - light
      - sensor
      - switch
      - sun

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  auth_providers:
     - type: homeassistant
     - type: trusted_networks
       trusted_networks:
         - 192.168.1.0/24
         - 127.0.0.1
         - fd00::/8

homekit:
 - filter: !include filter.yaml
   entity_config:
      camera.vacuum_map:
        stream_source: !secret vacuum_map_url
      media_player.tv:
        feature_list:
          - feature: on_off
          - feature: play_pause
          - feature: play_stop
          - feature: toggle_mute

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.0/24

input_boolean: !include inputs.yaml

ios:

light: !include lights.yaml

logbook:

lovelace:
  mode: yaml
  resources: !include resources.yaml

map:

media_player: !include media_players.yaml

mobile_app:

mqtt:
  discovery: true
  broker: !secret mqtt_broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

person: !include persons.yaml

recorder:
  exclude:
    domains:
      - camera

remote:
  - platform: xiaomi_miio
    host: !secret miremote_ip
    token: !secret miremote_token
    name: MiRemote

script: !include scripts.yaml

scene: !include scenes.yaml

sensor: !include sensors.yaml

smartir:

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret

sun:

switch: !include switches.yaml

system_health:

weather: !include weather.yaml

zeroconf:

zone: !include zones.yaml
