alexa:
  smart_home:
    filter:
      exclude_domains:
        - automation
        - group
        - media_player

api:

automation: !include automations.yaml

binary_sensor: !include binary_sensors.yaml

camera: !include cameras.yaml

cloud:

config:

device_tracker: !include device_trackers.yaml

discovery:
  ignore:
    - igd
    - google_cast
    - plex_mediaserver

fontawesome:
  regular:
  solid:
  brands:

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml

history:
  include:
    domains:
      - binary_sensor
      - device_tracker
      - light
      - sensor
      - sun

homeassistant:
  packages: !include_dir_named packages
  auth_providers:
     - type: homeassistant
     - type: trusted_networks
       trusted_networks:
         - 192.168.1.0/24
         - 127.0.0.1
         - fd00::/8

homekit:

http:
  base_url: !secret baseurl
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.0/24

input_boolean: !include inputs.yaml

ios:

light: !include lights.yaml

logbook:

lovelace:
  mode: yaml

map:

media_player: !include media_players.yaml

mobile_app:

mqtt:
  discovery: true
  broker: !secret mqtt_broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

person:

recorder:
  exclude:
    entities:
      - sensor.vacuum_map

script: !include scripts.yaml

scene: !include scenes.yaml

sensor: !include sensors.yaml

sun:

switch: !include switches.yaml

system_health:

weather: !include weather.yaml

zeroconf:

zone: !include zones.yaml
