- platform: "mqtt"
  name: "Bedroom_light"
  state_topic: "zigbee2mqtt/Bedroom bulb"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  schema: "json"
  command_topic: "zigbee2mqtt/Bedroom bulb/set"
  unique_id: "0x14b457fffe44348c_light"
  optimistic: true
  retain: true
  device:
    identifiers:
      - "mqtt"
      - "zigbee_0x14b457fffe44348c"
    manufacturer: "IKEA"
    model: "LED1836G9"
    name: "TRADFRI LED bulb E27 WW 806lm"
    sw_version: "Zigbee2mqtt 1.6.0"
