- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_secret
- platform: androidtv
  name: Fire TV
  device_class: firetv
  host: !secret firetv_ip
  apps:
    com.amazon.tv.launcher: "Fire TV"
  turn_on_command: "input keyevent 3"
  turn_off_command: "input keyevent 223"
  state_detection_rules:
    'com.amazon.tv.launcher':
      - 'standby'
    'com.netflix.ninja':
      - 'media_session_state'
    'com.ellation.vrv':
      - 'audio_state'
    'com.plexapp.android':
      - 'paused':
          'media_session_state': 3  # this indentation is important!
          'wake_lock_size': 1       # this indentation is important!
      - 'playing':
          'media_session_state': 3  # this indentation is important!
      - 'standby'
    'com.amazon.avod':
      - 'playing':
          'wake_lock_size': 4  # this indentation is important!
      - 'playing':
          'wake_lock_size': 3  # this indentation is important!
      - 'paused':
          'wake_lock_size': 2  # this indentation is important!
      - 'paused':
          'wake_lock_size': 1  # this indentation is important!
      - 'standby'
