resources:
  - type: js
    url: /local/custom_cards/icloud3-event-log-card.js?v=1.000
  - type: js
    url: /local/kiosk.js
  - type: module
    url: /community_plugin/aftership-card/aftership-card.js
title: Vancouver Home
views:
  - badges:
      - entity: device_tracker.iphone11pro
      - entity: person.karine
      - entity: sun.sun
      - entity: binary_sensor.iss
    cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - aspect_ratio: 75%
        camera_image: camera.snow_radar
        entity: camera.snow_radar
        hold_action:
          action: none
        show_state: false
        type: picture-entity
      - aspect_ratio: 54%
        camera_image: camera.mt_seymour
        camera_view: live
        entity: camera.mt_seymour
        hold_action:
          action: none
        show_state: false
        tap_action:
          action: more-info
        theme: Backend-selected
        type: picture-entity
      - entities:
          - entity: sensor.vancouver
          - entity: sensor.tunis
          - entity: sensor.paris
          - entity: sensor.london
          - entity: sensor.new_york
          - entity: sensor.tokyo
        show_header_toggle: false
        title: World Clock
        type: entities
      - cards:
          - cards:
              - entity: light.bulb_light
                name: Bulb
                type: light
              - entity: light.bedroom
                name: Bedroom Lights
                type: light
            type: horizontal-stack
          - cards:
              - entity: switch.led_lights_switch
                hold_action:
                  action: more-info
                icon: 'mdi:lightbulb'
                name: LED
                tap_action:
                  action: toggle
                theme: slate
                type: entity-button
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: binary_sensor.front_door_contact
          - entity: binary_sensor.motion_2_occupancy
          - entity: binary_sensor.motion_1_occupancy
        show_header_toggle: false
        title: Motion
        type: entities
      - type: 'custom:aftership-card'
        entity: sensor.aftership
        title: Packages
    path: dashboard
    theme: slate
    title: Dashboard
  - badges: []
    cards:
      - entities:
          - input_text.zigbee2mqtt_old_name
          - input_text.zigbee2mqtt_remove
          - input_text.zigbee2mqtt_new_name
        title: Input text
        type: entities
      - entities:
          - script.zigbee2mqtt_remove
          - script.zigbee2mqtt_rename
        title: Script
        type: entities
      - entities:
          - input_select.zigbee2mqtt_log_level
        title: Input select
        type: entities
      - entities:
          - automation.zigbee2mqtt_log_level
          - switch.zigbee2mqtt_main_join
        title: Automation
        type: entities
      - entities:
          - entity: automation.turn_on_the_living_room_lights
          - entity: automation.turn_on_the_living_room_lights_when_motion_is_detected
          - entity: automation.turn_on_the_living_room_lights_dimmed
          - entity: automation.turn_off_the_living_room_lights_using_switch
          - entity: automation.dim_living_room_when_media_is_playing
          - entity: automation.undim_living_room_lights_when_media_is_paused
        title: Lights
        type: entities
    path: zigbee-control
    title: Zigbee control
  - badges:
      - entity: sensor.transmission_active_torrents
      - entity: sensor.transmission_status
      - entity: sensor.transmission_completed_torrents
      - entity: sensor.transmission_started_torrents
      - entity: sensor.transmission_up_speed
      - entity: sensor.transmission_down_speed
    cards:
      - entities:
          - entity: switch.transmission_turtle_mode
          - entity: switch.transmission_switch
        title: Switch
        type: entities
      - entity: media_player.spotify
        type: media-control
    panel: false
    path: default_view
    theme: slate
    title: Media
