custom_header:
  compact_mode: true
  background: rgba(155, 155, 155, 0.25)
background: var(--background-image)
title: Vancouver Home
views:
  # Main panel
  - path: dashboard
    title: Dashboard
    icon: fas:tachometer-alt
    panel: true
    badges:
      - entity: person.kais
      - entity: person.karine
    cards:
      - type: horizontal-stack
        cards:
          - type: horizontal-stack
            title: Room control
            cards:
              - type: vertical-stack
                cards:
                  - type: entities
                    entities:
                      - type: custom:slider-entity-row
                        entity: light.bedroom
                        hide_state: true
                        name: Light
                      - entity: sensor.bedroom_light
                        name: Lux
                      - entity: sensor.bedroom_temperature
                        name: Temperature
                      - entity: sensor.bedroom_humidity
                        name: Humidity
                      - entity: binary_sensor.motion_1_occupancy
                        name: Occupancy
                      - entity: switch.vacuum_bedroom
                        name: Vacuum
                    show_header_toggle: false
                    title: Bedroom
                  - type: entities
                    entities:
                      - type: custom:slider-entity-row
                        entity: light.kitchen
                        hide_state: true
                        name: Light
                      - entity: switch.vacuum_kitchen
                        name: Vacuum
                    show_header_toggle: false
                    title: Kitchen
                  - type: entities
                    entities:
                      - entity: switch.vacuum_bathroom
                        name: Vacuum
                    show_header_toggle: false
                    title: Bathroom
              - type: vertical-stack
                cards:
                  - type: entities
                    entities:
                      - type: custom:slider-entity-row
                        entity: light.bulb_light
                        hide_state: true
                        name: Lamp
                      - entity: switch.led_lights_switch
                        name: LED lamp
                      - entity: sensor.livingroom_light
                        name: Lux
                      - entity: sensor.livingroom_temperature
                        name: Temperature
                      - entity: sensor.livingroom_humidity
                        name: Humidity
                      - entity: switch.vacuum_living_room
                        name: Vacuum
                    title: Living room
                    show_header_toggle: false
                  - type: entities
                    entities:
                      - entity: binary_sensor.front_door_contact
                        name: Door
                      - entity: binary_sensor.motion_2_occupancy
                        name: Occupancy
                      - entity: switch.vacuum_hall
                        name: Vacuum
                    show_header_toggle: false
                    title: Entrance
          - type: vertical-stack
            cards:
              - type: 'custom:xiaomi-vacuum-card'
                entity: vacuum.rockrobo
                vendor: valetudo
                name: 'Vacuum'
              - type: picture-entity
                aspect_ratio: 55%
                camera_image: camera.vacuum_map
                entity: camera.vacuum_map
                hold_action:
                  action: none
                show_state: false
            title: Vacuum

  # Weather panel
  - path: weather
    title: Weather Forecast
    icon: fas:snowflake
    badges:
      - entity: sun.sun
      - entity: sensor.moon
      - entity: binary_sensor.iss
    cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - entities:
          - entity: sensor.vancouver
          - entity: sensor.tunis
          - entity: sensor.paris
          - entity: sensor.london
          - entity: sensor.new_york
          - entity: sensor.tokyo
        show_header_toggle: false
        title: World Clock
        type: entities
      - cards:
          - aspect_ratio: 75%
            camera_image: camera.snow_report
            entity: camera.snow_report
            hold_action:
              action: none
            show_state: false
            type: picture-entity
          - aspect_ratio: 54%
            camera_image: camera.mt_seymour
            camera_view: live
            entity: camera.mt_seymour
            hold_action:
              action: none
            show_state: false
            tap_action:
              action: more-info
            type: picture-entity
        type: vertical-stack
  # Network/Zigbee settings
  - badges: []
    icon: fas:network-wired
    cards:
      - entities:
          - input_text.zigbee2mqtt_old_name
          - input_text.zigbee2mqtt_remove
          - input_text.zigbee2mqtt_new_name
        title: Input text
        type: entities
      - entities:
          - script.zigbee2mqtt_remove
          - script.zigbee2mqtt_rename
        title: Script
        type: entities
      - entities:
          - input_select.zigbee2mqtt_log_level
        title: Input select
        type: entities
      - entities:
          - automation.zigbee2mqtt_log_level
          - switch.zigbee2mqtt_main_join
        title: Automation
        type: entities
    path: zigbee-control
    title: Zigbee control
