resources:
  - type: js
    url: /local/kiosk.js
  - type: js
    url: /community_plugin/lovelace-valetudo-map-card/valetudo-map-card.js
  - type: js
    url: /local/custom_cards/icloud3-event-log-card.js?v=1.000
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - type: module
    url: /community_plugin/aftership-card/aftership-card.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - url: /local/slider-entity-row.js
    type: module
custom_header:
  compact_mode: true
  background: rgba(155, 155, 155, 0.25)
background: var(--background-image)
title: Vancouver Home
views:
  # Main panel
  - path: dashboard
    title: Dashboard
    icon: fas:tachometer-alt
    badges:
      - entity: device_tracker.iphone11pro
      - entity: person.karine
    cards:
      - cards:
          - entities:
              - entity: binary_sensor.front_door_contact
              - entity: binary_sensor.motion_2_occupancy
              - entity: binary_sensor.motion_1_occupancy
              - entity: sensor.livingroom_temperature
                name: Living room
              - entity: sensor.livingroom_humidity
                name: Living room
              - entity: sensor.bedroom_temperature
                name: Bedroom
              - entity: sensor.bedroom_humidity
                name: Bedroom
            show_header_toggle: false
            title: Sensors
            type: entities
          - type: entities
            show_header_toggle: false
            title: Lights
            entities:
              - entity: switch.led_lights_switch
                name: LED
              - type: custom:slider-entity-row
                entity: light.bulb_light
                name: Bulb
              - type: custom:slider-entity-row
                entity: light.bedroom
                name: Bedroom
              - type: custom:slider-entity-row
                entity: light.kitchen
                name: Kitchen
        type: vertical-stack
      - cards:
          - type: 'custom:xiaomi-vacuum-card'
            entity: vacuum.rockrobo
            vendor: valetudo
            name: 'Vacuum'
          - cards:
              - entities:
                  - entity: switch.vacuum_charger
                    name: Outlet
                  - entity: switch.vacuum_charger_usb
                    name: USB
                title: Vacuum base
                type: entities
              - entities:
                  - entity: switch.power_outlet
                    name: Outlet
                  - entity: switch.power_outlet_usb
                    name: USB
                title: Power outlet
                type: entities
            type: horizontal-stack
          - type: entities
            show_header_toggle: false
            entities:
              - entity: switch.vacuum
                name: House
              - entity: switch.vacuum_living_room
                name: Living Room
              - entity: switch.vacuum_kitchen
                name: Kitchen
              - entity: switch.vacuum_hall
                name: Hall
              - entity: switch.vacuum_bedroom
                name: Bedroom
              - entity: switch.vacuum_bathroom
                name: Bathroom
            title: Vacuum zone
        type: vertical-stack
      - type: 'custom:valetudo-map-card'
        entity: sensor.vacuum_map
        rotate: -90
        crop:
          top: 100
          bottom: -100
          left: 0
          right: 0
        min_height: 0
        map_scale: 2

  # Weather panel
  - path: weather
    title: Weather Forecast
    icon: fas:snowflake
    badges:
      - entity: sun.sun
      - entity: sensor.moon
      - entity: binary_sensor.iss
    cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - entities:
          - entity: sensor.vancouver
          - entity: sensor.tunis
          - entity: sensor.paris
          - entity: sensor.london
          - entity: sensor.new_york
          - entity: sensor.tokyo
        show_header_toggle: false
        title: World Clock
        type: entities
      - cards:
          - aspect_ratio: 75%
            camera_image: camera.snow_report
            entity: camera.snow_report
            hold_action:
              action: none
            show_state: false
            type: picture-entity
          - aspect_ratio: 54%
            camera_image: camera.mt_seymour
            camera_view: live
            entity: camera.mt_seymour
            hold_action:
              action: none
            show_state: false
            tap_action:
              action: more-info
            type: picture-entity
        type: vertical-stack

  # Shipping panel
  - title: Packages
    panel: true
    icon: fas:shipping-fast
    cards:
      - entity: sensor.aftership
        title: Packages
        type: 'custom:aftership-card'

  # Network/Zigbee settings
  - badges: []
    icon: fas:network-wired
    cards:
      - entities:
          - input_text.zigbee2mqtt_old_name
          - input_text.zigbee2mqtt_remove
          - input_text.zigbee2mqtt_new_name
        title: Input text
        type: entities
      - entities:
          - script.zigbee2mqtt_remove
          - script.zigbee2mqtt_rename
        title: Script
        type: entities
      - entities:
          - input_select.zigbee2mqtt_log_level
        title: Input select
        type: entities
      - entities:
          - automation.zigbee2mqtt_log_level
          - switch.zigbee2mqtt_main_join
        title: Automation
        type: entities
      - entities:
          - entity: automation.turn_on_the_living_room_lights
          - entity: automation.turn_on_the_living_room_lights_when_motion_is_detected
          - entity: automation.turn_on_the_living_room_lights_dimmed
          - entity: automation.turn_off_the_living_room_lights_using_switch
          - entity: automation.dim_living_room_when_media_is_playing
          - entity: automation.undim_living_room_lights_when_media_is_paused
        title: Lights
        type: entities
    path: zigbee-control
    title: Zigbee control

  # Torrent/Media center
  - badges:
      - entity: sensor.transmission_active_torrents
      - entity: sensor.transmission_status
      - entity: sensor.transmission_completed_torrents
      - entity: sensor.transmission_started_torrents
      - entity: sensor.transmission_up_speed
      - entity: sensor.transmission_down_speed
    icon: fas:cloud-download-alt
    cards:
      - entity: media_player.spotify
        type: custom:mini-media-player
        artwork: cover
        source: icon
      - entities:
          - entity: switch.transmission_turtle_mode
          - entity: switch.transmission_switch
        title: Switch
        type: entities
    panel: false
    path: default_view
    title: Media
